name: Bandit Analysis

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 0 * * *'  # Run daily at midnight
    - cron: '0 * * * *'  # Run every hour

jobs:
  run_bandit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2.3.4

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install Bandit
        run: pip install bandit
        
   
      - name: Run Bandit
        run: python compliance_check.py https://github.com/DEBANJANAB/Vulnerable-Code-Snippets.git "Vulnerable-Code-Snippets"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Configure Git
        run: |
          git config --global user.name 'DEBANJANAB'
          git config --global user.email 'debanjana.bhattacharyya9818@gmail.com'

      - name: Commit and push CSV file
        run: |
          git add Vulnerable-Code-Snippets/compliance_report.csv
          git commit -m 'Add compliance report'
          git pull --rebase origin main
          git push
       
        
      - name: Upload CSV Output
        uses: actions/upload-artifact@v2
        with:
          name: Compliance Report
          path: Vulnerable-Code-Snippets/compliance_report.csv



               
 

