name: Bandit Analysis

permissions:
  contents: write

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 0 * * *'  # Run daily at midnight
    - cron: '0 * * * *'  # Run every hour

jobs:
  run_bandit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: pip install bandit pandas requests

      - name: Run Bandit Analysis
        run: python compliance_check.py https://github.com/DEBANJANAB/Vulnerable-Code-Snippets
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Clone target repository
        run: |
          git clone https://github.com/DEBANJANAB/Vulnerable-Code-Snippets.git Vulnerable-Code-Snippets
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Copy CSV to target repository
        run: |
          cp compliance_report.csv Vulnerable-Code-Snippets/
          ls -la Reports

      - name: Configure Git
        run: |
          git config --global user.name 'DEBANJANAB'
          git config --global user.email 'debanjana.bhattacharyya9818@gmail.com'
      
      - name: Commit and push to target repository
        run: |
          cd Reports
          git status
          git add compliance_report.csv
          git commit -m 'Add compliance report'
          git pull --rebase
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload CSV Output
        uses: actions/upload-artifact@v2
        with:
          name: Compliance Report
          path: compliance_report.csv
